= Passive FTP with NGINX
:showtitle:
:toc: left

== Introduction

NGINX Plus has been able to support Passive FTP since R18. See the https://www.nginx.com/blog/nginx-plus-r18-released[port-ranges example] in the release announcement. However this doesn't 
allow load balancing over multiple FTP servers, because the `$server_port` variable cannot be 
used in an upstream group. At least not up to and including NGNIX Plus R22.

The solution is to use the https://nginx.org/en/docs/njs/[NJS Module] to inspect the control channel
and populate the Key/Value store with the upstream used so that it can be referenced in the data 
connection. The http://nginx.org/en/docs/http/ngx_http_keyval_module.html[Key/Value Store]
is only available with https://www.nginx.com/products/nginx/[NGINX Plus] so these configs will not work
with NGINX Open Source.

== NGINX Options

There are two ways to process the FTP connections, using simple "passthrough" or "inspection"

* Passthrough - The connection is not inspected by NGINX - this will work for all FTP and
FTPS connections, whether you use implicit (connect to TLS port) or explicit (connect to FTP and use
startTLS). 

* Inspection - This only works with plain FTP or implicit FTPS (ie doesn't support startTLS).
NGINX inspects the requests and knows which ports to expect data connections on. It allows you to block 
connections from clients to data ports which have not been negotiated on the control channel. You also have the option to log commands and file transfers.

* TODO - Investigate support for startTLS on "inspected" connections. 

****
With Passthrough The FTP Server needs to know the VIP of the load balancer, and publish it in PASV
responses. This will fail if the FTP server can't do that.
****

=== Persistence

You shouldn't need to use session persistence in the `upstream` configuration, but some FTP clients will
open multiple control connections to the server, and each of these connections could be load balanced to a
different upstream.

To avoid this we use the variable `$upstream_server` which is set to link the data connection to the 
control channel to also apply to any additional control connections. This "persistence" will timeout
with the entry in the key/value store. Any new connections afterwards will be load balanced normally.

----
    map $server_port $mapped_control {
        21          vsftpd_21_backend;   # default port 21 upstream
        990         vsftpd_990_backend;  # default port 990 upstream
    }

    map $upstream_server $mapped_server {
      ~[0-9]+     $upstream_server:$server_port;
      default     $mapped_control;
    } 
----

The alternative to this is to use an IP Hash in the upstream groups.

----
    upstream vsftpd_990_backend {
        hash $remote_addr;
        zone vsftpd_990 64k;
        server vsftpd:990 resolve;
    }   
----


== A simple example (Passthrough)

The configuration in `passive_passthrough_nginx.conf` can load balance FTP and both implicit and explicit FTPS
without doing any decryption on the NGINX Plus instance. 

We use a https://nginx.org/en/docs/stream/ngx_stream_js_module.html[js_filter] directive in the configuration to run the `passthrough_control_channel` function from `passive_ftp.js`.

The function watches the control channel for responses from the FTP server and updates the
`$upstream_server` variable in the key/value store. When a client connects on a data port, the variable has
already been set by the control channel and so the data connection is sent to the same upstream server.

The `keyval_zone` directive sets a timeout on the IP mapping, by default it will stay in effect for 60 seconds.
You can change the timeout by updating the keyval_zone section of the config. The timeout should be at least as
long as your `proxy_timeout` on the control connection.

----
keyval_zone zone=ftp_ports:128k timeout=60s;
keyval $remote_addr $upstream_server zone=ftp_ports;
----

This is the simplest and most flexible example, but it doesn't allow for inspection of the traffic when you're using FTPS. If you want to inspect the traffic then you should use "Inspection"

== A more complex example (Inspection)

The configuration in `passive_inspect_nginx.conf` can be used to load balance implicit FTPS only. If you want to
load balance plain old FTP, then remove the SSL directives from the configuration. But we all know that would be
a terrible idea!

In the "inspection" configuration we can run a more secure service. We only allow clients to connect to the FTP
servers data port when we have seen a corresponding `PASV` response.

The Data Channels will be logged in the access log along with the FTP (list, store, or retrieve) command which
was used with them.

== FTP with Source NAT (Proxy Protocol example)

In cases where the FTP server is behind a gateway performing Source NAT you can tunnel the original client IP
through to NGINX using proxy protocol. In this example we'll cover the tweaks which need to be made to both a
front-end and a back-end NGINX for this to work. 

When using proxy_protocol between multiple NGNIX instances for FTP, then you can use either pass-through or
inspection configuration. Although it makes sense to only use the full inspection on one of them. It shouldn't
matter which NGINX (if any) does the full inspection.

In the front-end NGINX, you can use either pass-through or inspection and then enable proxy_protocol in the
server block. The passthrough example would look like this:

----
    # FTP Service listening on port 21
    server {
        listen 21;
        status_zone ftp_server;
        js_filter passthrough_control_channel;
        proxy_protocol on;
        proxy_pass $mapped_server;
    }
----

On the backend NGINX instance, you would enable proxy_protocol on the `listen` directive like this:

----
    # FTP Service listening on port 21
    server {
        listen 21 proxy_protocol;
        status_zone ftp_server;
        js_filter passthrough_control_channel;
        proxy_pass $mapped_server;
    }
----

The other change you need to make on the backend NGINX is to replace `$remote_addr` with `$proxy_protocol_addr`
and the `$remote_port` with `$proxy_protocol_port` in the logs and the variable mappings. See below for both
passthrough and inspection examples:

.passthrough log
----
    log_format basic 'FTP: $server_addr $server_port $remote_addr [ $time_local ] '
                 '( $proxy_protocol_addr -> $upstream_server ) '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time';

----

.inspection log
----
    log_format basic 'FTP: $server_addr $server_port $remote_addr [ $time_local ] '
                 '( $proxy_protocol_addr -> $mapped_server ) "$data_xfer" '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time';
----

.pass-through keyvals
----
    keyval $proxy_protocol_addr $upstream_server zone=ftp_ports;
----

.inspection keyvals
----
    keyval "$proxy_protocol_addr:$proxy_protocol_port" $data_port zone=ftp_ports;
    keyval "$proxy_protocol_addr:$data_port" $upstream_socket zone=ftp_ports;
    keyval "$proxy_protocol_addr:$data_port:xfer" $xfer zone=ftp_ports;

    keyval "$proxy_protocol_addr:$server_port" $data_server zone=ftp_ports;
    keyval "$proxy_protocol_addr:$server_port:xfer" $data_xfer zone=ftp_ports

    keyval "$proxy_protocol_addr" $upstream_server zone=ftp_ports;
----

With these changes you can use either pass-through or inspection methods on the front-end and back-end NGINX
instances.

:wq

